### ISSUE TITLE
Can't use dispensers.

### ISSUE THREAD

**Issue by ghost** [InsightsPlugin/Insights#141]
Minecraft: 1.17.1
Paper: 325
Insights: 6.7.2

Whenever I try to use a Dispenser it doesn't dispense anything.
I confirmed by testing dispensers without Insights. They started dispensing stuff again.

**Comment by FrankHeijden** [comment]
Interesting, the only piece of code that handles dispensers is this:
https://github.com/InsightsPlugin/Insights/blob/e2828f071026be057fda6e13ccaaf09fd520119f/Insights/src/main/java/dev/frankheijden/insights/listeners/BlockListener.java#L149-L181

which does not cancel/modify the event or anything like that. I will have to test later.

**Comment by Raesak** [comment]
It wasn't working because I had the setting "settings.redstone-update-limiter.block-outside-region" to true.
I thought that setting would only determine if the update limiter would affect Redstone updates outside of regions.
Apparently it determines if Redstone updates can only happen inside of regions.
