### ISSUE TITLE
Blocks placed in creative mode with RestrictedCreative plugin aren't deducted from the limit after breaking them

### ISSUE THREAD

**Issue by UDPSendToFailed** [InsightsPlugin/Insights#174]
As the title says. 

If I place a block that's limited with Insights in creative mode with the RestrictedCreative plugin and then break it, the count won't decrease, it sticks after breaking the block as if it's still placed. This results in the player's limit eventually maxing out even if they broke their creative-placed blocks already.

RestrictedCreative plugin's source code: https://bitbucket.org/Prunt/restrictedcreative/src/master/

Versions:

Insights 6.12.1-SNAPSHOT
GriefPreventionAddon 2.1.0
GriefPrevention 16.18
RestrictedCreative 2.5.2

**Comment by FrankHeijden** [comment]
Problem here is this line - https://bitbucket.org/Prunt/restrictedcreative/src/d2a29ea376bcc3edfa3a9ce671c74785c8b40b00/P_RestrictedCreative/src/me/prunt/restrictedcreative/listeners/BlockBreakListener.java#lines-146

they break block(s) while also cancelling the blockbreakevent. If the event is cancelled, Insights cannot know of the change.

Since this plugin breaks multiple blocks as well, likely an addon should be made for compatibility.
