### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PapiCapi** [InsightsPlugin/Insights#27]
Here is the error shown in the console : http://prntscr.com/tuhznr
I'm using Spigot ( This server is running CraftBukkit version git-Spigot-0287a20-7560f5f (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) ) and Insights 3.5.9.

**Comment by FrankHeijden** [comment]
Hey, thank you for reporting this!

The issue here is that you're using CraftBukkit, a version Spigot built on top of and Insights doesn't support CraftBukkit.

I suggest you download Paper (a fork of Spigot, which provides a multitude of performance improvements over spigot, and it is just the recommended version to go to on your version, MC 1.16.1).

I am sorry, but I cannot fix your issue!
