### ISSUE TITLE
Feature request : Lands add-on and placeholders.

### ISSUE THREAD

**Issue by Gohu1** [InsightsPlugin/Insights#63]
Hi, i wanted to propose you some suggestions. The plugin is very good, one of the only to make this, but it could be even more perfect. Why do not add some placeholders which could display the allowed limit for a type of block, or the amount of this block the player has already set. An other thing would be to hook into more claims plugins like Lands, which is becoming one of the most used claim plugin today.

Thank you for reading.

**Comment by FrankHeijden** [comment]
The lands addon feature sounds good, however the placeholder feature I am not really sure how that would work out. Limits are dynamic, and multiple limits can be active for the same user. Are you suggesting something like this?:

* **%insights_limits_count_<MATERIAL>%** to display the limit for a user given material
* **%insights_limits_max_<MATERIAL>%** to display the max amount for a given material

Due to the way Insights works, these placeholders might not always be available when the placeholder is being fetched. Insights only scans the chunk/region when a block is being placed, thus the first placeholder can only become active after the region/chunk has been scanned. I could add a language locale which will display "**N/A**" when the region/chunk hasn't been scanned yet.

**Comment by Gohu1** [comment]
That'd be perfect, talking about placeholders it is exactly what i was thinking about. Even if it scans chunk/region, it would allow in a first time to display these placeholders correctly inside claims. And possibly, you should see if it is possible instead of displaying a "N/A" to keep the last value in memory.

**Comment by FrankHeijden** [comment]
The addon is available here: [LandsAddon](https://github.com/InsightsPlugin/LandsAddon)
